### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by waldyrious** [TeamOfOne/psc16-team33#32]
"Smart Guitar" is so cliché and uninformative. Let's use this issue to brainstorm some options. I'll start:
- **DynaChords** (highlighting the interactivity)
- **InteraChords** (same)
- **OpenChords.js** / **OpenGuitar.js**
- **ChordPlay.js** (a _wordplay_ with _Coldplay_... get it?... guys?... ok, I'll show myself out.)
- **Underschord** (highlightling the chord identifying feature -- as in "understand" + "chords".
  Bonus: sounds like "underscore", which is... completely useless, but a fun fact nevertheless)
- **OhMyChord** (dunno, just for fun :P)

so, yeah... bring your wild ideas on :D

**Comment by PedroGomes** [comment]
I think from all of them I like ChordPlay the better

**Comment by waldyrious** [comment]
It's also my favorite, I'm glad you like it :D

**Comment by PedroGomes** [comment]
Another idea: **VisuaChords**

Because we can visualize the chords

**Comment by fjsnogueira** [comment]
VisuaChords.com is available, so is my favorite right now

**Comment by waldyrious** [comment]
just because it is available, or you actually like it more than the others?

**Comment by fjsnogueira** [comment]
yes, I prefer to look at names that have a .com available (if possible), besides that, my favourite would be OpenChords

**Comment by waldyrious** [comment]
I don't think it's a good idea to give so much weight in the naming choice to whether a nice domain is available. Let's avoid big trademarks, sure, but other than that, it would be nicer to pick something we like for itself, and use the domain availability as more of a tie-breaker than a primary criterion. But let me know if you think otherwise :)

**Comment by elincognito** [comment]
Just to add one to the mix i like **MyChords**

**Comment by waldyrious** [comment]
Yet another idea is to make some wordplay with the two meanings of "string" (in music and programming)

**Comment by fjsnogueira** [comment]
What about **Guitarjs**?

**Comment by waldyrious** [comment]
That's waaay to generic and has been used by a lot of projects already: four projects named [guitarjs](https://github.com/search?q=guitarjs), one named [guitar.js](https://github.com/chezstov/guitar.js), and there's also [chords.js](https://github.com/einaregilsson/chord.js) by the way. It appears that the `<generic-word>.js` ship has sailed :P

Incidentally, these may be stuff we'll want to take a look at to see if there are stuff we could incorporate.

**Comment by waldyrious** [comment]
After some synchronous discussion (on slack), we've settled on **guitarjs**. Hurray! 🎉
